version: '3.3'

services:
  transcriber:
    build: ./env/
    network_mode: "host"
    ports: 
      - "8000"
    container_name: transcriber
    command: "python3 /code/app.py"
    volumes:
      - $PWD:/code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]