FROM nvcr.io/nvidia/pytorch:22.12-py3

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && apt-get -y install ffmpeg
RUN pip3 install --no-cache-dir openai-whisper Flask

RUN pip3 install faster-whisper pydub 

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code