FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

RUN apt-get -y update && apt-get -y install ffmpeg
RUN apt update && apt install -y python3 python3-pip
RUN pip3 install torch --index-url https://download.pytorch.org/whl/cu118
RUN pip3 install openai-whisper openai 
RUN pip3 install pydub flask requests

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code